[2023-06-08T18:33:48.750+0300] {processor.py:157} INFO - Started process (PID=16041) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:33:48.751+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:33:48.752+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:33:48.751+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:33:48.791+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:33:48.790+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 8, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:33:48.791+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:33:49.232+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.482 seconds
[2023-06-08T18:34:27.038+0300] {processor.py:157} INFO - Started process (PID=16092) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:34:27.039+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:34:27.039+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:34:27.039+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:34:27.070+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:34:27.070+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 8, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:34:27.070+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:34:27.410+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.372 seconds
[2023-06-08T18:35:30.875+0300] {processor.py:157} INFO - Started process (PID=16180) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:35:30.876+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:35:30.877+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:35:30.877+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:35:30.911+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:35:30.911+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 8, in <module>
    from venv.airflow.dags.crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'venv.airflow'
[2023-06-08T18:35:30.912+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:35:31.272+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.397 seconds
[2023-06-08T18:36:34.073+0300] {processor.py:157} INFO - Started process (PID=16288) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:36:34.074+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:36:34.074+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:36:34.074+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:36:34.106+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:36:34.105+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 8, in <module>
    from venv.airflow.dags.crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'venv.airflow'
[2023-06-08T18:36:34.106+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:36:34.441+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.369 seconds
[2023-06-08T18:37:37.601+0300] {processor.py:157} INFO - Started process (PID=16383) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:37:37.603+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:37:37.603+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:37:37.603+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:37:37.634+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:37:37.633+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 12, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:37:37.634+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:37:37.970+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.369 seconds
[2023-06-08T18:38:43.282+0300] {processor.py:157} INFO - Started process (PID=16476) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:38:43.284+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:38:43.284+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:38:43.284+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:38:43.315+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:38:43.314+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 12, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:38:43.315+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:38:43.645+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.363 seconds
[2023-06-08T18:39:45.996+0300] {processor.py:157} INFO - Started process (PID=16588) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:39:45.997+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:39:45.997+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:39:45.997+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:39:46.029+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:39:46.027+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 12, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:39:46.029+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:39:46.360+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.365 seconds
[2023-06-08T18:40:48.225+0300] {processor.py:157} INFO - Started process (PID=16681) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:40:48.226+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:40:48.227+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:40:48.227+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:40:48.257+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:40:48.256+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 12, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:40:48.257+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:40:48.588+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.363 seconds
[2023-06-08T18:41:50.310+0300] {processor.py:157} INFO - Started process (PID=16762) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:41:50.311+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:41:50.312+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:41:50.311+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:41:50.342+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:41:50.341+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 12, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:41:50.342+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:41:50.672+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.363 seconds
[2023-06-08T18:42:53.580+0300] {processor.py:157} INFO - Started process (PID=16857) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:42:53.581+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:42:53.581+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:42:53.581+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:42:53.614+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:42:53.613+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 8, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:42:53.614+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:42:53.954+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.375 seconds
[2023-06-08T18:43:55.951+0300] {processor.py:157} INFO - Started process (PID=16946) to work on /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:43:55.952+0300] {processor.py:826} INFO - Processing file /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py for tasks to queue
[2023-06-08T18:43:55.952+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:43:55.952+0300] {dagbag.py:541} INFO - Filling up the DagBag from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:43:55.983+0300] {logging_mixin.py:149} INFO - [2023-06-08T18:43:55.982+0300] {dagbag.py:350} ERROR - Failed to import: /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
Traceback (most recent call last):
  File "/Users/dogukanulu/opt/anaconda3/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py", line 8, in <module>
    from crypto_data_stream import data_stream
ModuleNotFoundError: No module named 'crypto_data_stream'
[2023-06-08T18:43:55.984+0300] {processor.py:838} WARNING - No viable dags retrieved from /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py
[2023-06-08T18:43:56.316+0300] {processor.py:179} INFO - Processing /Users/dogukanulu/Desktop/codebase/crypto_api_kafka_airflow/venv/airflow/dags/crypto_data_stream_dag.py took 0.364 seconds
